### ISSUE TITLE
iOS Binaries

### ISSUE THREAD

**Issue by i5hi** [StackmateNetwork/stackmate-core#15]

**Comment by i5hi** [comment]
`make ios` works on m1 Mac. 

For now binaries are looking good. Will close this issue when the next 0.10.1 release is out with new iOS binaries.

**Comment by MrUnfunny** [comment]
Hey @i5hi thanks for all your work. Can we use it in flutter for iOS? I don't have much experience with ffi. What would I need to do to integrate this for iOS?

**Comment by i5hi** [comment]
Hey @MrUnfunny! Thanks.

Over the next month we should have stable IOS binaries as part of the releases so you won't have to build them yourself.

The main build process is handled in the makefile. 

make android builds android targets and make iOS builds iOS binaries.

[the-stackmate](https://github.com/StackmateNetwork/the-stackmate) is a reference for how to use the library for both android and iOS. it currently only supports android. It has an update-core.sh script which gets the binaries from the releases which the dart ffi can use.

**Comment by MrUnfunny** [comment]
I will be waiting for the release. I'm currently trying different approaches to build a BTC wallet in flutter. I wanted to ask if stackmate supports multi-signature because I could not find it in the readme.

**Comment by i5hi** [comment]
yes, it has full support for multi signature. 

You have to write a multisig policy and use the compile() function from stackmate-core which returns a descriptor. 

This descriptor can be used just like a single sig descriptor with all the wallet functions. 

The main difference is in build() - you have a variable called policy_path which you will have to specify for multisig descriptor wallets. 

This is the beauty of descriptor and bdk - a multisig wallet is 90% the same as a single sig wallet. 

I would recommend spending some time with bdk and bdk-cli 

https://bitcoindevkit.org/bdk-cli/introduction/

Once you understand this, you will be able to understand the stackmate-core ffi and then more easily create user experiences in flutter with this descriptor library.

**Comment by MrUnfunny** [comment]
@i5hi thanks for the link. I didn't have much understanding of the differences between singlesig and multisig wallets as I'm still learning most bitcoin concepts. BDK docs will surely be helpful.

**Comment by i5hi** [comment]
Join their discord group if you need any help

**Comment by i5hi** [comment]
Closing this. Moving to bdk-flutter and this repo will be deprecated.
